[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wibesocket"
version = "0.0.1"
description = "Minimal fast WebSocket client bindings for WibeSocket C core"
requires-python = ">=3.8"


